version: '3.8'  # Use the desired Docker Compose version

networks:
  custom_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.32.0.0/16

services:
  redis:
    restart: always
    container_name: netprobe-redis
    image: "redis:latest"
    volumes:
      - ./config/redis/:/etc/redis/
    networks:
      - custom_network  # Attach to the custom network

  netprobe:
    restart: always
    container_name: netprobe-probe
    build: .
    volumes:
      - .:/netprobe_lite
    environment:
      MODULE: "NETPROBE"
    networks:
      - custom_network  # Attach to the custom network

  presentation:
    restart: always
    container_name: netprobe-presentation
    build: .
    volumes:
      - .:/netprobe_lite
    environment:
      MODULE: "PRESENTATION"
    networks:
      - custom_network  # Attach to the custom network

  prometheus:
    restart: always
    container_name: netprobe-prometheus
    image: "prom/prometheus"
    volumes:
      - ./config/prometheus/:/etc/prometheus/
    networks:
      - custom_network  # Attach to the custom network

  grafana:
    restart: always
    image: grafana/grafana-enterprise
    container_name: netprobe-grafana
    volumes:
      - ./config/grafana/datasources/:/etc/grafana/provisioning/datasources/
      - ./config/grafana/dashboards/:/etc/grafana/provisioning/dashboards/
      - ./config/grafana/json/:/var/lib/grafana/dashboards/
    ports:
      - '4000:3000'
    networks:
      - custom_network  # Attach to the custom network
